[2021-08-27 17:13:32 +0300] [39917] [INFO] Starting gunicorn 20.1.0
[2021-08-27 17:13:32 +0300] [39917] [INFO] Listening at: http://0.0.0.0:5000 (39917)
[2021-08-27 17:13:32 +0300] [39917] [INFO] Using worker: sync
[2021-08-27 17:13:32 +0300] [39919] [INFO] Booting worker with pid: 39919
[2021-08-27 17:13:32 +0300] [39919] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/media/garry/Working/Work/drf_blog/drfBlog_venv/lib/python3.8/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/media/garry/Working/Work/drf_blog/drfBlog_venv/lib/python3.8/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/media/garry/Working/Work/drf_blog/drfBlog_venv/lib/python3.8/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/media/garry/Working/Work/drf_blog/drfBlog_venv/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/media/garry/Working/Work/drf_blog/drfBlog_venv/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/media/garry/Working/Work/drf_blog/drfBlog_venv/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/media/garry/Working/Work/drf_blog/drfBlog_venv/lib/python3.8/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'config'
[2021-08-27 17:13:32 +0300] [39919] [INFO] Worker exiting (pid: 39919)
[2021-08-27 17:13:32 +0300] [39917] [INFO] Shutting down: Master
[2021-08-27 17:13:32 +0300] [39917] [INFO] Reason: Worker failed to boot.
[2021-08-27 17:17:29 +0300] [40100] [INFO] Starting gunicorn 20.1.0
[2021-08-27 17:17:29 +0300] [40100] [INFO] Listening at: http://0.0.0.0:5000 (40100)
[2021-08-27 17:17:29 +0300] [40100] [INFO] Using worker: sync
[2021-08-27 17:17:29 +0300] [40102] [INFO] Booting worker with pid: 40102
[2021-08-27 17:17:29 +0300] [40102] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/media/garry/Working/Work/drf_blog/drfBlog_venv/lib/python3.8/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/media/garry/Working/Work/drf_blog/drfBlog_venv/lib/python3.8/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/media/garry/Working/Work/drf_blog/drfBlog_venv/lib/python3.8/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/media/garry/Working/Work/drf_blog/drfBlog_venv/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/media/garry/Working/Work/drf_blog/drfBlog_venv/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/media/garry/Working/Work/drf_blog/drfBlog_venv/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/media/garry/Working/Work/drf_blog/drfBlog_venv/lib/python3.8/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'config'
[2021-08-27 17:17:29 +0300] [40102] [INFO] Worker exiting (pid: 40102)
[2021-08-27 17:17:29 +0300] [40100] [INFO] Shutting down: Master
[2021-08-27 17:17:29 +0300] [40100] [INFO] Reason: Worker failed to boot.
